### ISSUE TITLE
OpenAPI 3 relative server urls are marked as invalid.

### ISSUE THREAD

**Issue by tdextrous** [PayU/api-schema-builder#59]
When using relative server urls in OpenAPI 3.0 like shown:
```json
"servers": [
  {
    "url": "/api/foo"
  }
]
```
An error is thrown:
```
TypeError [ERR_INVALID_URL]: Invalid URL: /api/foo
```

Stack trace points to the error occurring [here](https://github.com/PayU/api-schema-builder/blob/889970fd93f9dd51c90b56f46146796495905961/src/index.js#L40). It seems that all values in the `url` field are assumed to be complete urls. Is there some way we can check for a relative url before passing to the `URL` constructor?

**Comment by spasquali-ww** [comment]
This also fails as INVALID_URL

```
servers:
  - url: '{protocol}://api.example.com'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
```
