### ISSUE TITLE
Getting an error 'exclusiveMinimum should be number' when setting exclusiveMinimum 

### ISSUE THREAD

**Issue by kobik** [PayU/api-schema-builder#86]
It seems that exclusiveMaximum and exclusiveMinimum are not properly supported by the package.

According to [OpenApi specs](https://swagger.io/docs/specification/data-models/data-types/) both exclusiveMaximum and exclusiveMinimum should be boolean, but when passing the below property definition it throws an error
```yaml
      exchange_rate:
        type: number
        format: double
        minimum: 0
        exclusiveMinimum: true
```

```
properties['exchange_rate'].exclusiveMinimum should be number
```

this is because according to the json schema specs exclusiveMaximum and exclusiveMinimum should be passed as a number
https://json-schema.org/understanding-json-schema/reference/numeric.html#range
